---
os: linux
dist: xenial
language: python

# Use the docker for testing
services:
- docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:

# Install python module, including ansible
- test ! -f requirements.txt      || pip install -r requirements.txt
- test ! -f requirements-test.txt || pip install -r requirements-test.txt

# Check ansible version
- ansible --version

# Check molecule version
- molecule --version


script:
- molecule test


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
