---
- name: Getent passwd 0
  become: False
  vars:
    ansible_become: False
  register: getent_passwd_result
  ansible.builtin.raw: getent passwd 0
  failed_when: False
  changed_when: False

- name: Set __root_user__
  vars:
    __root_user__: "{{ (getent_passwd_result.rc | d(1) == 0) | ternary((getent_passwd_result.stdout_lines | first | d('root:')).split(':')[0], 'root') }}"
  block:
  - name: Try disable become
    register: try_disabled_become
    become: False
    become_user: "{{ __root_user__ }}"
    vars:
      ansible_become: False
      ansible_become_user: "{{ __root_user__ }}"
    ansible.builtin.raw: id -u
    failed_when: >-
      try_disabled_become.rc is not defined
      or try_disabled_become.rc != 0
      or try_disabled_become.stdout_lines is not defined
      or not try_disabled_become.stdout_lines
    changed_when: False

  - name: Set_fact root_need_become and root_user
    ansible.builtin.set_fact:
      root_user: "{{ __root_user__ }}"
      root_need_become: "{{ try_disabled_become.stdout_lines | last != '0' }}"

- name: Require the root permission
  register: can_become_as_root
  become: "{{ root_need_become }}"
  become_user: "{{ root_user }}"
  vars:
    ansible_become: "{{ root_need_become }}"
    ansible_become_user: "{{ root_user }}"
  ansible.builtin.raw: id -u
  changed_when: False
  failed_when: >-
    can_become_as_root.rc is not defined
    or can_become_as_root.rc != 0
    or can_become_as_root.stdout_lines is not defined
    or can_become_as_root.stdout_lines | select('search', '.') | list | length < 1
    or can_become_as_root.stdout_lines | select('search', '.') | list | last != "0"
