---
- name: Test role for hosts should_pass
  hosts: should_pass
  gather_facts: False
  roles:
  - role: ansible-require-become-root-role

- name: Test role for hosts should_fail
  hosts: should_fail
  gather_facts: False
  tasks:
  - block:
    - name: include role
      include_role:
        name: ansible-require-become-root-role
    - name: result=false
      set_fact:
        role_result: False
    rescue:
    - name: result=true
      set_fact:
        role_result: True

### INLINE VERIFY

- name: Verify resulting facts of the role for hosts should_pass
  hosts: should_pass
  gather_facts: False
  tasks:
  - name: check facts
    assert:
      that:
      - "ansible_user == 'root' or root_need_become"
      - "ansible_user != 'root' or not root_need_become"
      - "root_user == 'root'"

- name: Verify resulting facts of the role for hosts should_fail
  hosts: should_fail
  gather_facts: False
  tasks:
  - name: assert expected fail task
    assert:
      that:
      - "role_result"
      - "can_become_as_root is failed"
