---
dependency:
  name: shell
  command: |
    set -ex
    id
    python3 --version
    pip3 install -U pip
    pip3 --version
    ansible --version
    pip3 install -U passlib ansible-lint
    ansible-lint --version
    git config --global --add safe.directory "`pwd`"

lint: |
  set -ex
  ansible-lint --show-relpath

driver:
  name: docker

platforms:
- name: test-require-become-root-1
  image: python:3-alpine
  groups:
  - should_pass
  - as_root
- name: test-require-become-root-2
  image: python:3-alpine
  groups:
  - should_fail
  - as_guest
- name: test-require-become-root-3
  image: python:3-alpine
  groups:
  - should_pass
  - as_admin

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
    connection:
      pipelining: True
  inventory:
    group_vars:
      as_root:
        ansible_user: root
      as_guest:
        ansible_user: userGuest
      as_admin:
        ansible_user: userAdmin
        ansible_become: True
        ansible_become_user: root
