---
- name: Prepare
  hosts: all
  gather_facts: False
  vars:
    # directly run as root
    ansible_user: root

  tasks:
  - name: Install sudo
    ansible.builtin.package:
      name: sudo
      state: present

  - name: Enable wheel group
    ansible.builtin.lineinfile:
      name: /etc/sudoers
      state: present
      regexp: '^%wheel\s'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create userGuest
    ansible.builtin.user:
      name: userGuest
      password: "{{ '123456' | password_hash }}"

  - name: Create userAdmin
    ansible.builtin.user:
      name: userAdmin
      password: "{{ '123456' | password_hash }}"
      group: wheel
