---
name: ci workflow
"on": push

jobs:
  test-job:
    name: test the role
    runs-on: ubuntu-22.04
    steps:
    - name: print versions
      run: |
        set -x
        uname -a
        id
        python3 --version
        pip3 --version
        ansible --version
        docker version

    - uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"
    - uses: gofrolist/molecule-action@v2
      env:
        ANSIBLE_ROLES_PATH: ".."
      with:
        molecule_working_dir: "${{ github.repository }}"

  deploy-job:
    name: deploy the role on tag
    runs-on: ubuntu-22.04
    needs: test-job
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: publish the role to Galaxy
      uses: robertdebock/galaxy-action@1.2.1
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
        git_branch: ${{ github.ref_name }}
