---
name: ci workflow
"on": push

jobs:
  test-job:
    name: test the role
    runs-on: ubuntu-22.04
    steps:
    - name: print versions
      run: |
        set -x
        uname -a
        id
        python3 --version
        pip3 --version
        ansible --version
        docker version
        pwd

        #- name: prepare tests
        #run: |
        #set -x
        #pip3 install -r requirements.txt

    - uses: actions/checkout@v3
      with:
        path: "${{ github.repository }}"
    - uses: gofrolist/molecule-action@v2
      with:
        molecule_working_dir: "${{ github.repository }}"

  lint-job:
    name: lint codes
    runs-on: ubuntu-22.04
    env:
      ANSIBLE_ROLES_PATH: ".."
    steps:
    - uses: actions/checkout@v3
    - name: prepare lint
      run: |
        pip3 install -r requirements.txt
        pip3 install passlib ansible-lint
        ansible-lint --version
    - name: lint
      run: ansible-lint --show-relpath

  deploy-job:
    name: deploy the role on tag
    runs-on: ubuntu-22.04
    needs: [test-job, lint-job]
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: publish the role to Galaxy
      uses: robertdebock/galaxy-action@1.2.1
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
        git_branch: ${{ github.ref_name }}
